version: "3"

services:
  redis:
    image: redis
    container_name: redis_db
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"] # disable persistence
    ports:
      - 6379:6379
  api:
    build:
      context: ./api
    container_name: api_server
    ports:
      - 8090:8080
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 8080:80
